grep -B 1 -i "$2" $1/system.trc* | grep " 01:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 02:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 03:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 04:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 05:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 06:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 07:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 08:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 09:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 10:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 11:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 12:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 13:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 14:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 15:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 16:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 17:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 18:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 19:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 20:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 21:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 22:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 23:" | wc -l
grep -B 1 -i "$2" $1/system.trc* | grep " 24:" | wc -l
